services:
  - type: worker
    name: ai-solarbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
    autoDeploy: true
    branch: main 